#!/bin/bash
#Menu

echo -e "  Daftar Perintah:"
echo -e "* menu       : menampilkan daftar perintah"
echo -e "* user-baru  : membuat akun SSH & OpenVPN"
echo -e "* trial      : membuat akun trial"
echo -e "* hapus-user : menghapus akun SSH & OpenVPN"
echo -e "* cek        : cek user login"
echo -e "* member     : daftar member SSH & OpenVPN"
echo -e "* resv       : restart service dropbear, webmin"
echo -e "               squid3, OpenVPN dan SSH"
echo -e "* reboot     : reboot VPS"
echo -e "* tes-speed  : speedtest VPS"
echo -e "* info       : menampilkan informasi sistem"
echo -e "* about      : info script auto install"
echo -e "* exit       : keluar dari Putty/Connecbot/"
echo -e "               JuiceSSH"
echo -e ""
echo -e "Mod by BAT"
echo -e ""